language: node_js
node_js:
  - 8
  - 6
cache:
  directories:
    - ~/.npm
notifications:
  email:
    recipients:
      - arizzitano@edx.org
      - jbradley@edx.org
    on_success: always
    on_failure: always
  hipchat:
    rooms:
      secure: iAwlvLMl/Qfv/wI4vbwpo3B0X/f+F5gL+sra0IBf3/wgaY8BuE/PzxrIP+PAF31nAil5gGD3LQvQ/vk/CZhkWgkQGQndK2aYHhUaSmJbCLtIwg6NX+YBz34vGZJawQzf3BDOglx6new+OYjAZtbP0noyMCL6hwp3HmflT+OMI6rhUU35dwQ4GjGSPYkjtdQZHosT5zcungpaBuGRtnUVKPLWBaa1Wl9NK3Vp9GEq5TaR7xg7wNk6dDnMXiHHxb5xp8acFWpf3yCX7NCouW6oWaFx/o4/SvGUFL9hr2pW7yKVEc59spaI/aZ8LNm94iIgFImlTAYdtErmjJytZORgt6AFF90Fbe38ntFjVdo2F/8/qgzzn+GkknPyYXZC/io2jX5919WZLQg2nOAqQyDUa5m0k11YfC7h0E+FldbJKcDmI9CWfzhGJGTXIaQCSkRq2tWfUC9mxO7ssZl+B3u9Ywv+F22QYF46bfsJP+PsLYXDBBDLnCD+zfuOaxP9RPiqRMEkM1QYFlNX0Kl1YsN3a2SparzjWbuKA63HTCMBL+f4npeYI6fkPHxDeligFUzlMeJIWKBnh7T5ZaHMR1B9icq7HOzPuEQ8LChgkeymGsvoU2euH8nbCmHiWafbGAZp39FDKj68YoFdUX3sV8xn9/INyU6j+C4NtKCPFfbC33E=
before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - npm run lint
  - npm run test
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - npm run coveralls
  - npm run storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: .out
  on:
    branch: master
